### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by programmercube** [pranaygp/vscode-css-peek#101]
- Issue Type: `Bug`
- Extension Name: `vscode-css-peek`
- Extension Version: `4.0.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by pranaygp** [comment]
@programmercube can you add more details to this issue. I'm not sure what the problem you're experiencing is.
