### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by Slulego** [pranaygp/vscode-css-peek#11]
I hope I'm not just missing something right in front of my face.

VS Code: 1.18.0
Windows 10

I've tried:

- Open Html file with a stylesheet link.
- Create element with a id or class.
- Set different colors to the elements in the stylesheet.
- Tried all the shortcuts in the Readme file.
- F12 says "No definition found for 'x'.
- Try placing the css in a <style> tag.
- Try disabling all my other extensions.

Nothing is working.

**Comment by JBelkin** [comment]
Running into the same issues on Windows 7, VS Code 1.18.0

**Comment by mbl912** [comment]
i have same problem. I try JBelkin comment, but nothing is working.
Can anybody help my pls.?
Thanks.

**Comment by mbl912** [comment]
@Slulego it works?

**Comment by pranaygp** [comment]
This seems to be working just fine on my end. I'm running VSCode Version 1.18.1

I tested it using the included test files (https://github.com/pranaygp/vscode-css-peek/tree/master/test/test_files). If you go to [example.html](https://github.com/pranaygp/vscode-css-peek/blob/master/test/test_files/example.html#L5) and Cmd + click on "test" (or place your cursor on the anywhere in the word, and Cmd + E) the extension works as expected.

**Comment by JBelkin** [comment]
Updated to 1.18.1
Same issue, dev tools has no errors either.

**Comment by JBelkin** [comment]
@pranaygp If it would help I can screen share and let you take a look at the environment.

**Comment by pranaygp** [comment]
@JBelkin that would be lovely. Could you also link me to a Github repo of the codebase you're testing this on so I can test it locally?

**Comment by JBelkin** [comment]
@pranaygp It's even happening with the test folder for me.
If you have time tomorrow we can coordinate some call to go over everything.

**Comment by pranaygp** [comment]
@JBelkin happy to do so. :)

**Comment by pranaygp** [comment]
@Slulego, @mbl912 :
I spoke with @JBelkin and ascertained that he was accidentally using the keybinding for "Peek Implementation" instead of "Peek Definition". It worked correctly after using the right keybinding. 

Let me know if that's the same error you're facing. It should work correctly

**Comment by Slulego** [comment]
@pranaygp I've tried all the shortcuts, right click options and running through "ctrl+shift+p". Is there some line I can modify to fix it? I've tried searching to see if I need to replace "cmd" with "ctrl" or any keybindings but no luck.

**Comment by catarino** [comment]
having the same problems mentioned even with the new 1.3.3 update

**Comment by Slulego** [comment]
Version 1.3.3 is working on my work computer (Windows 7)!
I'll test it later on my own computer.

**Comment by catarino** [comment]
update: following https://github.com/pranaygp/vscode-css-peek/issues/13#issuecomment-347361909 I've found that this might be an issue with LESS. 

I'm currently working on 2 projects. One in LESS and the other in plain CSS. CSS Peek works as expected with CSS but no LESS.

**Comment by pranaygp** [comment]
@Slulego glad to hear it works for you now

@catarino yup, it could be an issue with less support. I plan to fix that along with the new rewrite for v2 which I will release soon. Stay tuned :)

**Comment by Slulego** [comment]
@pranaygp I got home after work and tried to test it and it is still not working on my personal computer (Windows 10). 
I've tried reinstalling Code and removing the Roaming files but it's still not working. I'm so lost as to why it's just my computer.

**Comment by catarino** [comment]
@pranaygp I can confirm it's a less issue. 

And it's great to know that you're working on a fix for that.

In any case, thx so much for your work.

**Comment by pranaygp** [comment]
@Slulego I don't have a way to test this on Windows 10. Can you try testing it on the `test_files` directory (from this repo) on your Windows 10 machine, with the latest version of CSS peek. You SHOULD expect the same behaviour between Windows 7 and Windows 10

**Comment by pranaygp** [comment]
The only thing I can think of from my codebase is I use the glob pattern `**/*.css` for stylesheet files, but I know in Windows, the file separator is `\`. I wonder if different windows versions deal with this differently

**Comment by Slulego** [comment]
@pranaygp Ok, so I tested it on my Windows 10 tablet and it worked perfectly. So I uninstalled VS Code and removed (renamed) the folders "C:\Users\Name\AppData\Roaming\Code" and "C:\Users\Name\.vscode" Then I reinstalled VS Code and it is finally working on my main machine! Yay!

**Comment by catarino** [comment]
hmm, still not working that great with .less problems. any update on this?

**Comment by pranaygp** [comment]
@catarino I rewrote the entire plugin, and ensured less support in Version 2.0.0
Can you update to the latest version and test it again. If it still doesn't work, send me a link to a github repo where you're trying that and it fails so that I can try and replicate it locally 😄

**Comment by mocombeg** [comment]
I am having this same issue... I've uninstalled and reinstalled it and I am still having this issue can anyone help with the latest version of VS Code and CSS Peek?

**Comment by Gabgab2003** [comment]
Same issue here, maybe its because my code is on an external hard drive (D:\), will update accordingly

**Comment by catarino** [comment]
all good now. for a few motnhs now. sorry I should've updated status.

**Comment by ksw25** [comment]
peek operation is not working when I do ctrl + shift + f12.

**Comment by awardo** [comment]
CSS Peek was not working for me.  I got it to work in VS Code by installing the extension: HTML CSS Support.  Once this is installed and enabled, you can peek the CSS code by pressing ctrl (or command on mac) + hover with mouse. To go to that class in your css file, press ctrl and click the class name.

**Comment by akar-jaza** [comment]
It didn't work i really need this extension

**Comment by Imad-MACHI** [comment]
I did the same as @awardo did, and it worked without any issues

**Comment by isaacfink** [comment]
I had the same issue and installing the CSS HTML support plugin fixed it, just make sure to restart the editor

**Comment by November1984** [comment]
It's have a problems with support break-spaces in files paths. That why it's doesn't work. I think

**Comment by SomeEarth86** [comment]
Quite late to this discussion but, it wasn't working for me as well, (v4.2.2). Uninstalled and reinstalled it and it works.(Mac user here)
