### ISSUE TITLE
Unable to peek

### ISSUE THREAD

**Issue by hemanthvhs** [pranaygp/vscode-css-peek#110]
Version - 4.2.0
Steps to reproduce

ISSUE-1

1. Create the class in HTML. ```<h1 class="heading-1">Hello World</h1>```
2. Add the CSS class.  ```.heading-1 {.......}```
3. Try to peek (CTRL + Click on the classname || F12 ) doesn't open the css file
4. Inorder to resolve the issue, close the vscode open it again then issue is resolved.

ISSUE-2

1. Change the CSS class. (Initial - heading-1 to head-1)
2. Now update the class in HTML. ```<h1 class="heading-1">Hello World</h1> to <h1 class="head-1">Hello World</h1>```
3. Try to peek (CTRL + Click on the classname) editor still opens the css file & highlights the class)
4. Inorder to resolve the issue, close the vscode open it again then issue is resolved.

**Comment by FrancisLydz1321** [comment]
what if neither of your recommendation doesn't solve the problem?

**Comment by fin-k** [comment]
I think this is auto refresh problem, I download this extension couple days ago and I have this problem until now. Below is the example, I moved `.clearfix` class but the peek still point to previous location.

![image](https://user-images.githubusercontent.com/10423383/185612036-7cd29400-467a-4031-856f-b3b9288a0fc4.png)

**Comment by pranaygp** [comment]
This has been fixed in version v4.3.4
