### ISSUE TITLE
No Definition found

### ISSUE THREAD

**Issue by mbl912** [pranaygp/vscode-css-peek#12]
Can anybody help me fix this problem? I try everything what i can i  found  on Internet and this Issues. :(
Know anybody how i can fix NO definition found. 
I've tried:

Open Html file with a stylesheet link.
Create element with a id or class.
Set different colors to the elements in the stylesheet.
Tried all the shortcuts in the Readme file.
F12 says "No definition found for 'span'.
Try placing the css in a <style> tag.
Try disabling all my other extensions.
Nothing is working. 
???

**Comment by pranaygp** [comment]
> F12 says "No definition found for 'span'.

actually makes sense. The extension doesn't *currently* support HTML tags. This was brought up in #10. Do try the extension with regular class names or ids and it should work.

something like:

test/index.html
```
<html>
  <body>
    <div class="someClass"> Hello </div>
  </body>
</html>
```

test/style.css
```
.someClass {
  color: #f00;
}
```

if you have a project liek that, and your cursor is on "someClass" in test/index.html, it should work for you as expected

**Comment by mbl912** [comment]
This thinks do everywhere. I wasn't in class. Cursor was on <h1> (not in class) and do it. 👍
