### ISSUE TITLE
Unable to install and start

### ISSUE THREAD

**Issue by hagyao520** [pranaygp/vscode-css-peek#121]
Is there a packaged Vscode VSIX installation file, otherwise it cannot be installed to Vscode, and it will be deleted if copied to the .vscode/extensions directory
![image](https://user-images.githubusercontent.com/24785603/142605037-e10fe1d8-0f1c-48e1-a261-2e3e4b73469f.png)

**Comment by pranaygp** [comment]
I'm not sure what you mean? Please use the marketplace to install it
