### ISSUE TITLE
Bad behavior

### ISSUE THREAD

**Issue by NikolayBalkandzhiyski** [pranaygp/vscode-css-peek#123]
Issue Type: <b>Bug</b>

Causing slowness when searching for symbols in project.
I do have a lot of Php and Laravel extensions, but this is not acceptable because the slowness make the VS code unusable in some basic cases

Extension version: 4.2.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:00:36.721Z)
OS version: Linux x64 5.11.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|15.52GB (3.84GB free)|
|Process Argv|. --crash-reporter-id ecd250cb-0402-4315-a05c-768d5d1ba2f9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246cf:30401891
pythonvs932:30405811
vscexrecpromptc:30404946
vscop804:30404766
vscop341:30404997

```

</details>

**Comment by fmp777** [comment]
This extension seems to be doing more than it says. There's no excuse for the cpu cycles it takes, and nonstop even while vscode is idle. On remote servers it was singlehandedly bringing down average resource servers. I've had to remove it, kill the 9 processes it had going, and delete all the files from vscode-server, because even after uninstalling via vscode, AND killing the processes, it started itself back up somehow.  SEEMS nefarious, and if its not, just very poorly programmed.

**Comment by pranaygp** [comment]
Definitely poor coding (I built this in my second year of my CS degree). It's not nefarious (feel free to inspect the code)

I'm happy to accept new maintainers given my current lack of time to keep this upto date
