### ISSUE TITLE
Nefarious extension or just poor coding?

### ISSUE THREAD

**Issue by fmp777** [pranaygp/vscode-css-peek#124]
This extension seems to be doing more than it says. There's no excuse for the cpu cycles it takes, and nonstop even while vscode is idle. On remote servers it was singlehandedly bringing down average resource servers. I've had to remove it, kill the 9 processes it had going, and delete all the files from vscode-server, because even after uninstalling via vscode, AND killing the processes, it started itself back up somehow.  SEEMS nefarious, and if its not, just very poorly programmed.

In any case, NOT worth its own overhead in its current condition, at least in my experience.

**Comment by pranaygp** [comment]
Definitely poor coding (I built this in my second year of my CS degree). It's not nefarious (feel free to inspect the code)

I'm happy to accept new maintainers given my current lack of time to keep this upto date
