### ISSUE TITLE
less files not working! 

### ISSUE THREAD

**Issue by andreskebe** [pranaygp/vscode-css-peek#13]
Tried with an existing project, with a new project, tried changing the stylesheets in the test folder to .less files and VS code does not recognize any of the classes or tags in less files! 

I'm on Mac OS 10.12.6 running VS Code 1.18.1

.css and .scss are working fine (tested it with the files in the test folder)

**Comment by pranaygp** [comment]
That's odd. 
There's a configuration option `css_peek.searchFileExtensions`, which, by default, supports
".css", ".less" and ".scss" file extensions. That said, for ".less" files, it also parses the less file using the less preprocessor (https://github.com/less/less.js). I suppose if your less file is invalid or doesn't get parsed correctly, it might not work?

I'll test it myself in a bit, and even add .less files to the test folder

**Comment by andreskebe** [comment]
I figured it was odd, since it was working perfectly with css and scss! 
I'll test it with a valid less file and will let you know. 

Were your tests successful? 
Thank you!

**Comment by pranaygp** [comment]
@andreskebe 
I am in the middle of a rewrite of the codebase for this extension (making use of the new [Language Server Protocol](https://github.com/Microsoft/language-server-protocol)).

I'll make sure to test and ensure less support when releasing the new version (2.0)

**Comment by pranaygp** [comment]
I think .less files are now working (update to version 2.0)

I've included a .less file in my test_files as well (manual testing) and I can confirm that the file works when I tested it.

Please re-open this issue if you're still having troubles after the update

**Comment by andreskebe** [comment]
Works perfectly! Thank you
