### ISSUE TITLE
CodeHelper CPU 100%

### ISSUE THREAD

**Issue by TimBroddin** [pranaygp/vscode-css-peek#132]
Hi,

I noticed that since last week the CodeHelper process was using 100% CPU of one core. While investigating I found out that it was caused by the CSS Peek plugin.

I didn't have a chance to look any deeper into it, but can do so, if you provide me some instructions.

Thanks!

**Comment by mitivil** [comment]
I noticed that this extension (CSS Peek) does not turn off even when I close this very VS.code, and the plugin continue to work and load my PC.

**Comment by pustovalov** [comment]
investigation about CPU load brought me here:
![Process Explorer 2023-02-27 16-31-38](https://user-images.githubusercontent.com/1568885/221608310-97d59952-be39-4702-b264-701a00bbba1c.jpg)

**Comment by pranaygp** [comment]
@mitivil @TimBroddin thanks for bringing these up. There are number of issues like this about CPU usage that I've been trying to look into. I'll keep you posted when I hear more - in the meantime, and help with a pull request to fix the issue will help too since I might be a bit slow on this

**Comment by pranaygp** [comment]
@pustovalov can you please provide any information on what workspace you opened when using CSS Peek? Specifically I'm curious how many .css, .less, and .sass files are in the workspace (excluding `node_modules`),

**Comment by pranaygp** [comment]
This has been fixed in version v4.3.4
