### ISSUE TITLE
Leaves behind right-click menu

### ISSUE THREAD

**Issue by Yaro-Maro** [pranaygp/vscode-css-peek#136]
When I uninstall the extension, it leaves behind a "Peek" right click menu, but does nothing. Restarting VSCode or removing shortcuts manually did not work.

Can you please please fix it so it also removes the right-click menu after an uninstall? That would be really appreciated.

**Comment by pranaygp** [comment]
The "Peek" right click menu is a [native VSCode feature](https://code.visualstudio.com/docs/editor/editingevolved#_peek) and is not something being added by this extension. This extension is just triggered by VSCode when you use that Peek button
