### ISSUE TITLE
Extension Maintainence

### ISSUE THREAD

**Issue by jha-om** [pranaygp/vscode-css-peek#138]
Hey @pranaygp, first of all thank u so much for this wonderful extension.
And just to confirm from you that on vs code extension marketplace this extension is showing as deprecated bcz is no longer maintained by the author(attached an image regarding it). It works absolutely fine for me until now but I thought just to bring this issue into the light so that u can focus onto it.

Would love to hear from you about it.

![image](https://github.com/pranaygp/vscode-css-peek/assets/94907651/6dbed256-0a08-48f1-a01c-417b7b0df83a)

**Comment by jjaimealeman** [comment]
I received the same notification.

But nothing seems to have been posted by the maintainer 🤔

**Comment by shpj123** [comment]
same here

**Comment by roelvangils** [comment]
The warning worried me too. It has 4,477,659 users (including me) and it still works fine, so I hope it continues to work! 🙏🏼

**Comment by pranaygp** [comment]
Hey thanks for letting me know about this. Yup, the extension still works and should not be deprecated. I'm looking into it now

**Comment by pranaygp** [comment]
@yCodeTech thanks for digging up that discussion thread - it's so strange they did this over a comment thread without reaching out directly to the extension author. In the past, Microsoft has reached out directly to me when major updates are made to the marketplace.

In any case, I've gone ahead and responded in that thread to let them know they should revert the decision :)
