### ISSUE TITLE
Not working after an HTML comment

### ISSUE THREAD

**Issue by ndstephens** [pranaygp/vscode-css-peek#14]
I can Hover, Peek, and Go To with any class in my HTML code before my first HTML comment, but nothing works following a comment.  If i delete the comment then it'll work for all that followed it.

Anyone else experience this issue?  I've disabled any comment related plugins I had.  I'm on Mac High Sierra(10.13.2), VSCode 1.18.1 and your latest version (2.0.2).  On a very small and simple project.  

Thanks.

**Comment by pranaygp** [comment]
Oh. That seems like an odd issue. I suppose it has something to do with the HTML scanner I'm using (https://github.com/Microsoft/vscode-html-languageservice). I'll try to dig into it soon and figure out if it's an error in CSS Peek, or a dependency

**Comment by emeydoubletee** [comment]
@pranaygp I've found a workaround. Although the extension stops working after a `<!---comment-->`, it will continue working if you use the `<comment>` element.

**Comment by pranaygp** [comment]
I don't know how valid [this page](https://html.com/tags/old-comment-tag/) is, but it seems to imply that `<comment>` is deprecated and not supported by some browsers today. I wouldn't recommend that as a solution.

I'll try to poke around this issue soon (currently in the middle of studying for exams at school) and try to fix the actual issue

**Comment by emeydoubletee** [comment]
So far I've tested it on both Firefox `57.0.1` and Chromium `63.0.3239.84` and it works.

**Comment by pranaygp** [comment]
fixed this in version 2.0.3

**Comment by vasilescur** [comment]
Verified, the fix works for me on Windows 10, plugin version `2.0.3`, VS Code `1.19.1`. Thanks!

**Comment by emeydoubletee** [comment]
Thank you @pranaygp. It works!

**Comment by AizatHawari** [comment]
Hi, I'm new to CSS peak, I just tried it and it's not working per issue [16](https://github.com/pranaygp/vscode-css-peek/issues/16)
It says no definition for class.. 
I am using
