### ISSUE TITLE
Ctrl+Shift+F12 not work

### ISSUE THREAD

**Issue by zhao511117** [pranaygp/vscode-css-peek#17]
when i press the F12,'GO TO' is worked,but press the 'Ctrl+Shift+F12' Why it doesn't work

**Comment by pranaygp** [comment]
Check your keyboard shortcut for "Peek Implementation". The default keyboard shortcut bindings are [here](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) but you can also [modify them](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor) if you'd like.
