### ISSUE TITLE
Possible to just search for scss class?

### ISSUE THREAD

**Issue by jaydickinson** [pranaygp/vscode-css-peek#18]
Is it possible to just search for the class with (cmd + shift + r or similar) and jump to the class without having to have it on an element and use go to definition?

Sometimes I just wanna jump to a class and know its name and searching would be great. I used to do this in sublime. Maybe I'm missing something where you can already do this?

Thanks

**Comment by pranaygp** [comment]
have you tried 'Ctrl+T'?

https://code.visualstudio.com/Docs/editor/editingevolved#_open-symbol-by-name

I don't know if CSS is supported, but I agree with your use case and think
it'd be useful. If it's not already built into VSCode for CSS Peek, I'm
happy to try and extend CSS Peek to do this

**Comment by jaydickinson** [comment]
Thanks for the reply! ctrl + T only brings up variables for me as I think they are all that is indexed but that's exactly the feature just with the option for classes etc to show as well. 

![screen shot 2018-01-11 at 09 12 42](https://user-images.githubusercontent.com/1121045/34817389-b583d610-f6af-11e7-838b-68ded3295b9e.png)

It would be great if you could look at extend CSS Peak to do this it's probably the only feature missing that I used to use in sublime.

**Comment by pranaygp** [comment]
I believe I've found what needs to be implemented for this:
https://code.visualstudio.com/docs/extensionAPI/language-support#_show-all-all-symbol-definitions-in-folder

Will try and get something up soon

**Comment by pranaygp** [comment]
@jaydickinson this is now implemented in version 2.1.0

Give it a try and let me know what you think

**Comment by jaydickinson** [comment]
NIce one seems to work well. pulls in node modules but I imagine If I exclude that from the project it will work better. 

Thanks!
