### ISSUE TITLE
Cannot read property 'offset' of null

### ISSUE THREAD

**Issue by rakhtar92** [pranaygp/vscode-css-peek#19]
While using` ctrl+shift+F12` or `ctrl+hover` on the class/id of an html element, getting the error : 

> Cannot read property 'offset' of null

**Comment by pranaygp** [comment]
@rakhtar92 can you please give me more information to help me reproduce this?

Can you share with me the repo that you tried to use this that gave you the error, or can you set up a simple example project to show me how to get this error? I'm unable to reproduce it and it works just fine on my end

**Comment by filiplh** [comment]
I have the same issue:
workspace is filled with angular projects.
I can see it scans a lot of css/less files, but finally fails on the above mentioned error-message.

Peek version 2.1.0
VS Code version 1.20.0

**Comment by pranaygp** [comment]
@filiplh could you share with me your project, or recreate a small angular project that has this issue and then send me the github url to it?

**Comment by pranaygp** [comment]
@VitalyName that's odd. I have a setup with the same file `.../bootstrap-3.3.6/less/mixins/grid.less`and the file has `&:extend(.clearfix all);`, however CSS Peek still works correctly in the repo without deleting those lines. 

Can you share your github repo with me so I can test it out locally? I wonder if something else is going wrong there.

**Comment by VitalyName** [comment]
**@pranaygp**
This does not happen:
1) When grid.less in node_modules.
2) When grid.less place above the opened directory (VScode->file->open folder).

See the README.md in this example  https://github.com/VitalyName/css-peek-crash-example.

**Comment by pranaygp** [comment]
Thank you for the crash example repo @VitalyName 
I was able to recreate a simple example of that issue happening and narrowed it down as stemming from `vscode-css-langaugeservice`.

I've opened up an upstream issue about this here: https://github.com/Microsoft/vscode-css-languageservice/issues/83 and will update the dep in my project once it's fixed there

**Comment by pranaygp** [comment]
I have a fix that makes it so this issue doesn't cancel all symbols and instead of prevents symbols from the affected file. I plan to ship it in the next version (2.1.1)
