### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Esteban-Rocha** [pranaygp/vscode-css-peek#23]
Extension has a memory leak, I was actually doing 0 css related work and still it eats the RAM.

![shot](https://user-images.githubusercontent.com/5914592/35419599-d64ff11e-0206-11e8-9656-ad4a987d92a5.png)

Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T15:57:21.071Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by pranaygp** [comment]
That actually makes sense. We use a language server which runs in the background and keeps a cache of all the css files in your workspace so that it can perform quick lookups when you Peek.

**Comment by Esteban-Rocha** [comment]
Hey! Thanks for your reply, and dammn! that's almost a GB there only on cache, is there a way to filter or exclude certain folders so the amount of RAM does not peak up so much?

**Comment by Esteban-Rocha** [comment]
Hopefully in future releases this ext. will implement such setting, I had to stop using this some months ago because it's unacceptable for me for a single ext to have 1GB ~ ram allocated, even so I'll love to use it again if this is fixed.
