### ISSUE TITLE
Support nesting classes in scss

### ISSUE THREAD

**Issue by PixelT** [pranaygp/vscode-css-peek#27]
![](https://i.imgur.com/NJX5sYR.png)

**Comment by pranaygp** [comment]
This seems like it's not a trivial fix (though it _could_ be? ¯\\_(ツ)_/¯)
I just find the right location by getting all the symbols from the appropriate LanguageService:

https://github.com/pranaygp/vscode-css-peek/blob/master/server/src/core/findDefinition.ts#L53

I'm definitely happy to accept a PR for this 👍

**Comment by pranaygp** [comment]
Fixed in 4.0.0
