### ISSUE TITLE
Prioritize non-minimized CSS files in Go To Definition

### ISSUE THREAD

**Issue by werecougar** [pranaygp/vscode-css-peek#28]
When using Go To Definition, if the definition is found in more than one CSS file, prioritize non-minified version.

For instance, a class ".home-page-intro" is found in "styles.css" as well as "styles.min.css." When I use Go To Definition, it loads "styles.min.css" first, with the option to switch to "styles.css." It would be much more helpful to open "styles.css" first.

**Comment by pranaygp** [comment]
You should be able to use the "css_peek.exclude" configuration to do this already. They arr regex, so just add a rule like "\w*\.min\.(c|sc|le)ss\b"
