### ISSUE TITLE
The extension is crushing in the newest version (1.23)

### ISSUE THREAD

**Issue by AngryBearr** [pranaygp/vscode-css-peek#32]
Here's the error I get, when I launch the editor:
**[Error - 11:08:24] Starting client failed
Error: spawn /usr/share/code/code EMFILE
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)**

Is there a way to solve that?

**Comment by AngryBearr** [comment]
Umm, hey @pranaygp 
Hmm... the extension just crashes, and all I get is that message in the terminal of the Visual Studio Code. If I can send you some logs, please tell how can I do that.

**Comment by pranaygp** [comment]
First, open up the output panel (you can find it in the Command Palette under "View: Toggle Output", and then click on "css-peek" on the right side dropdown of the new panel that shows up

![https://giphy.com/gifs/5kFVyWWsT038bLQXKm](https://media.giphy.com/media/5kFVyWWsT038bLQXKm/giphy.gif)

**Comment by AngryBearr** [comment]
You won't believe what happened... today I came at the office and voila, the extension just works. I swear it did crash on Thursday... I can't believe it woks now.
You can close the issue I guess... I hope I'll be lucky enough tomorrow.
Sorry *blush*

**Comment by pranaygp** [comment]
> You won't believe what happened

That's what I say everytime it happens to me 😛

Hope you enjoy using it and reopen this if the issue happens again 😄
