### ISSUE TITLE
No working in my pc, maybe i do something wrong?

### ISSUE THREAD

**Issue by Shlomo89** [pranaygp/vscode-css-peek#33]
I an new in vs code, so your extension might help me a lot after many years with brackets, but still not working.  I don't get how its wort, I installed the pick, put the cursor over the class and press all of the shortcuts, but still, it is not working, and advises?

**Comment by pranaygp** [comment]
@Shlomo89 Thanks for giving my extension a try 😁 

Make sure to search for the correct VSCode keyboard shortcut for "Peek Definition" (you should be able to google it, or check your settings). If you have an `html` file and a `css` file in the same workspace/project, and if you open up that project folder in VSCode (remember to open the folder, not just the file individually), then this extension will work correctly when you put your cursor on a tag/class/id in HTML and hit the shortcut.

Look at the gif on the Readme for an example:
![](https://github.com/pranaygp/vscode-css-peek/blob/master/working.gif)

**Comment by Shlomo89** [comment]
I put the cursor over the id and hit alt + f12 but the result is the same, a text pop up show up and it says:" no definition found for name {name of my class}, and yes it was "peek definition" shortcut, what else can I do?

**Comment by pranaygp** [comment]
hmm, can you show me a screen recording of what you're doing and maybe I can figure out what's up

**Comment by Shlomo89** [comment]
![image](https://user-images.githubusercontent.com/34649788/40747837-36947b36-6467-11e8-9d0e-6c182957b3d3.png)

**Comment by pranaygp** [comment]
Yeah, from that screenshot it seems like you don't have any CSS files in the project, so it won't be able to find CSS styles if there are none. Try creating a css file in the same project/directory in VSCode and then try this again
