### ISSUE TITLE
not working in vs code 1.24in macOS

### ISSUE THREAD

**Issue by zymr-keshav** [pranaygp/vscode-css-peek#35]
I have installed this useful extension but this is not at all working.

I am using .less files and vs code version is 1.24 and system is macOS v 10.13.3

**Comment by spencercap** [comment]
any word about this? seems like a great plugin, but it's also not working over here. 
vscode 1.25.1
macos 10.13.5

**Comment by Sh1noka** [comment]
Doesn't work on my Win 10. I use normal html and css.

```
Version: 1.27.1
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Archetecture: x64
```

**Comment by pranaygp** [comment]
Can you try updating to the latest version of CSS Peek (v2.2.0)

**Comment by Sh1noka** [comment]
I installed it yesterday. So I think it should be the newest version. Anyway, I will check the version number later.

**Comment by Sh1noka** [comment]
I have checked the version is 2.2.0 and it works now!

**Comment by pranaygp** [comment]
Awesome!

@zymr-keshav and @spencercap can you please try updating to 2.2.0 as well to see if it works. I'm closing this for now, but if it still doesn't work for you, report it here and I'll reopen the issue and work with you to fix it! 😁
