### ISSUE TITLE
Hover definition box not appearing

### ISSUE THREAD

**Issue by M0dSe7en** [pranaygp/vscode-css-peek#37]
When I hover over a CSS class name in a HTML file, like in the preview, a preview dialogue box does not appear; I can still use peak definition and goto but I want to see the CSS code without leaving the HTML file if possible. How can I resolve this?

**Comment by ChenZH097** [comment]
我也是这样。。。

**Comment by pranaygp** [comment]
This was an update to VSCode since I first released the extension: https://code.visualstudio.com/updates/v1_40#_definition-preview-hover-from-the-keyboard
