### ISSUE TITLE
Add Support for Handlebars.JS (.hbs)

### ISSUE THREAD

**Issue by ngurney** [pranaygp/vscode-css-peek#40]
Expected behavior: The exact same as when using CSS peek on a HTML file. 

Actual Behavior: When attempting to use CSS Peek with a .hbs file, it does not pull up any results. Always says "No Definition Found".

Not sure what limitations there are on this or if it is possible, but would love to see it!

Cheers,
Nick

**Comment by YoniSchirris** [comment]
Also awaiting this feature. Might have to switch back to another editor because of this, since I code everything in handlebars templates -- not being able to go to the definition of classes in older handlebars template files makes it cumbersome to use vscode.

**Comment by arch-stack** [comment]
Hey, can you guys try this and let me know if it works or gives a different message?
Not 100% sure if this will work but there's a chance

Change yous activeLanguages setting by adding "handlebars" to the list

```
"css_peek.activeLanguages": [
        "html",
        "ejs",
        "erb",
        "php",
        "javascriptreact",
        "typescriptreact",
        "typescript",
        "javascript",
        "handlebars"
    ]
```

**Comment by Amparose** [comment]
> Change your activeLanguages setting by adding "handlebars" to the list

Unfortunately that Hail Mary remains unanswered; adding "handlebars" to `css_peek.peekFromLanguages` (couldn't see activeLanguages in settings) doesn't do anything. Did try restarting VSC in case.

**Comment by Mordef** [comment]
Have added "twig" and "smarty"
works fine

**Comment by pranaygp** [comment]
These are now supported by default in the latest CSS Peek
