### ISSUE TITLE
[Error] Request textDocument/definition failed

### ISSUE THREAD

**Issue by daliri72** [pranaygp/vscode-css-peek#42]
When `ctr+hover` on a class on CSS show me this error
`Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'offset' of null
  Code: -32603 `
my projects is Angular 5

**Comment by murr4y** [comment]
Same here. VSCode 1.27.2

**Comment by pranaygp** [comment]
Can you update to CSS Peek 3.3.0+
A lot has changed and the issue is likely fixed.
If it's still an issue, can you please direct me a to a sample repo where I can reproduce this issue?

**Comment by pranaygp** [comment]
Closed
