### ISSUE TITLE
Option to exclude peek on html tags

### ISSUE THREAD

**Issue by Ventzy** [pranaygp/vscode-css-peek#47]
When I have angular component in HTML like
```
<my-component></my-component>
```
I prefer to go to component's .ts class file when I place the cursor over _my-component_ and press F3. It worked until I installed CssPeek. Now it shows css matches. CssPeek is still useful for other cases, but in this particular case, 99% I want to go to corresponding angular ts file. It will be great if there is a setting to ignore tags.

**Comment by pranaygp** [comment]
Agreed 😁

**Comment by arch-stack** [comment]
Do you guys still want this? I think it might be an easy change

**Comment by nerdmax** [comment]
+1!

**Comment by Ventzy** [comment]
Still wanted. I am not using the extension because of this.

**Comment by nerdmax** [comment]
+1

**Comment by pranaygp** [comment]
@arch-stack any ideas on how to do this?

**Comment by arch-stack** [comment]
Last time I looked I had an idea, just got lots going on right now 😛

If I find a little downtime I'll throw a branch together

**Comment by arch-stack** [comment]
I took a look around and I think I still need to learn the language server stuff some more

It seems that the action of presenting the definition in the popup is tied to the click/keypress action to go to definition

So I suspect (but I could be wrong) that in order for it to still work and not cause a go to definition action we might have to make it show in a different circumstance (like maybe hover)

**Comment by arch-stack** [comment]
I took a look around and I think I still need to learn the language server stuff some more

It seems that the action of presenting the definition in the popup is tied to the click/keypress action to go to definition

So I suspect (but I could be wrong) that in order for it to still work and not cause a go to definition action we might have to make it show in a different circumstance (like maybe hover)

**Comment by gvmohzibat** [comment]
+1
This is so annoying when using Angular. I'll have to uninstall the extension until it's fixed

**Comment by pranaygp** [comment]
Fixed in 4.0.0+.

There's now an option called "supportTags" that's enabled by default, but you can turn it off if you'd like
