### ISSUE TITLE
infinite loading in angular 4

### ISSUE THREAD

**Issue by vulkanosaure** [pranaygp/vscode-css-peek#5]
Hello,

i have a basic angular 4 project, where i'm editing html templace, and the code is place in various .css files (most common angular organization).
When i hover a class name from the HTML, i see a "loading..." label that never conclude. 
If i right click and click "Peek Definition", nothing happens.

I didn't touch to the settings : 
```
  "css_peek.activeLanguages": [
    "html",
    "ejs"
  ],

  // A list of extensions that should be tried for finding peeked files.
  "css_peek.searchFileExtensions": [
    ".css",
    ".scss",
    ".less"
  ],

  // Files are ignored from the CSS lookup if they match any of these Regular Expressions (regex).
  "css_peek.exclude": [
    "node_modules",
    "bower_components"
  ],
```
Cheers

**Comment by pranaygp** [comment]
There have been a lot of improvements on CSS Peek and the VSCode API since you opened this issue in 2017. It should be resolved, but please reopen if it's not @vulkanosaure and provide me a repo I can clone and test with to reproduce this issue
