### ISSUE TITLE
Not working on in case if CSS and HTML both are in same file.

### ISSUE THREAD

**Issue by bhalalapj** [pranaygp/vscode-css-peek#50]
I had a very long file and in head section I had written down CSS classes, I used classes in my HTML code, I installed this extension in my VS Code and try to go to definition of that **CSS class not able to do so**. 

Is there any other way or trick with I am missing over here to try out ?

**Comment by pranaygp** [comment]
It's not currently supported but is a feature that should exist. I've created #20 to track it
