### ISSUE TITLE
css_peek.exclude doesn't work

### ISSUE THREAD

**Issue by arnofly** [pranaygp/vscode-css-peek#51]
Hello,

On Windows 7 x64, I tried to set up the plugin with a fresh user folder of VS Code to avoid some conflict with other plugins, but I have always the same issue. The "css_peek.exclude" option has no effect. I add a folder to the option's array, but the plugin still search inside the folder.

Otherwise, your plugin is cool, thx!

**Comment by arch-stack** [comment]
Hey can you try this PR?
https://github.com/pranaygp/vscode-css-peek/pull/61

**Comment by pranaygp** [comment]
This was resolved in #61
