### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Aimakhede** [pranaygp/vscode-css-peek#52]
- Issue Type: `Performance`
- Extension Name: `vscode-css-peek`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.31.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\MIKE\pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by pranaygp** [comment]
Closing in favour of #62
