### ISSUE TITLE
Doesn't seem to work in my VSCode

### ISSUE THREAD

**Issue by nmaxcom** [pranaygp/vscode-css-peek#53]
Latest VSCode and css-peek extension, running on macOS 10.12.6.

I had forgotten I had this extension, so when I discovered it wasn't working, I reinstalled it. But it doesn't seem to work even with inline-declared CSS (`<style>` in the HTML) nor with bootstrap CDN `<link>`.

If I try 'Peek definition' ⌥F12 on an id that's declared within a style tag a few lines up:

![image](https://user-images.githubusercontent.com/8936090/51802291-a71f9300-2216-11e9-98c0-c9e1ef72cd04.png)

Same result when peeking classes loaded from the bootstrap file.

Trying 'Peek references' ⇧F12 on an inline defined item or one from bootstrap I also get the same result:

![image](https://user-images.githubusercontent.com/8936090/51802702-983adf80-221a-11e9-814c-eb8a69abda42.png)

I'm pretty sure I'm doing something wrong, but I don't know what it is.

**Comment by pranaygp** [comment]
@nmaxcom yeah, right now it only supports extenal stylesheets that you have available locally (i.e. in a dedicated `.css`, `.less` or `.sass` file. I'm planning to add support for`<style>` tags soon. Supporting external styles from bootstrap CDN unfortunately won't be possible 😢

**Comment by nmaxcom** [comment]
Oh, okay. I'll keep that in mind.

About not being able to support online styles, I think it wouldn't be that difficult to parse the HTML looking for those online *.css files, downloading them in a temp folder and use your "class/id searcher" against those as well, right?

Anyhow thanks for the answer and the plugin.

**Comment by pranaygp** [comment]
One problem I see with doing that is it gives you the false sense of ability to modify these CSS files that've been downloaded locally. You might open the file with the peek feature and modify it, but when you actually open your .html file it'll still be using the real file from CDN

**Comment by nmaxcom** [comment]
I see what you mean. I guess in those particular cases the peeker should act as read-only, maybe even adding a slight color difference to help understand it's read-only (I'm unaware of VSCode specifics to accomplish something like that). For example in CSS frameworks like Bootstrap, you'd never modify the Bootstrap codebase but you'd benefit greatly from getting all those classes available through your intellisense-like feature.

From where I'm standing that would be much better than not having it at all. Just my 2 cents.
