### ISSUE TITLE
Change highlighted style color?

### ISSUE THREAD

**Issue by kenw232** [pranaygp/vscode-css-peek#55]
How do I change the highlighted style block color?  Its light brown for me which makes it impossible to read anything.  Is this in my theme?

Screenshot: http://temp.extremehosting.ca/trash/color.png

**Comment by pranaygp** [comment]
yup! The theme decides this I believe but you can also customize it directly and override the highlight color: https://stackoverflow.com/a/43605752

Not a CSS Peek issue
