### ISSUE TITLE
Hightlight background color?

### ISSUE THREAD

**Issue by kenw232** [pranaygp/vscode-css-peek#58]
Does anyone know how to figure out which background/highlight color variable name this is so I can change it?  I tried every "workbench.colorCustomizations" color option (eg. "editor.selectionHighlightBackground", "editor.lineHighlightBackground", etc.) I can think of and nothing changes it.  It makes the entire extension useless.

http://temp.extremehosting.ca/trash/color.png

**Comment by pranaygp** [comment]
can you elaborate? The screenshot link doesn't work

**Comment by juventus18** [comment]
https://code.visualstudio.com/api/references/theme-color#peek-view-colors
