### ISSUE TITLE
Several search processes are started

### ISSUE THREAD

**Issue by roblourens** [pranaygp/vscode-css-peek#59]
From https://github.com/Microsoft/vscode/issues/70457

This line starts 3 searches, which can be expensive in large workspaces https://github.com/pranaygp/vscode-css-peek/blob/2b7708dbea34126b251e4eff9e6d9b1120718905/client/src/extension.ts#L111

Please consider a different approach
- Only do this work when a css file is actually opened, instead of searching the whole workspace for one
- Use a workspaceContains activationEvent, which is bound at 5s and will merge multiple patterns into one search, and will stop searching when one matching file is found
- Start just one search for all patterns, like `findFiles('{**/*.css, **/*.scss}')`

**Comment by arch-stack** [comment]
I made a PR to sort out a different issue, in the process I made an adjustment to that line above that should reflect your third point
Let me know if you think that's similar to what you expect
https://github.com/pranaygp/vscode-css-peek/pull/61

**Comment by pranaygp** [comment]
@arch-stack's PR fixed this and is included in the new release of 3.0.2
