### ISSUE TITLE
Change shortcut Ctrl+hover

### ISSUE THREAD

**Issue by fakhamatia** [pranaygp/vscode-css-peek#60]
How change Ctrl+hover shortcut?
[In Linux i have to change Alt](https://github.com/Microsoft/vscode/issues/28810#issuecomment-309676217)
And when change Ctrl hover not woke any more

**Comment by pranaygp** [comment]
You can change them with VSCode preferences (https://code.visualstudio.com/docs/getstarted/keybindings)

however, it looks like there might not (yet) be a way to customize the Ctrl+hover functionality (https://github.com/Microsoft/vscode/issues/46257)
