### ISSUE TITLE
希望能自动命名css

### ISSUE THREAD

**Issue by uxzhen** [pranaygp/vscode-css-peek#63]
Issue Type: <b>Feature Request</b>

哈哈哈，解决css命名困难证

Extension version: 2.2.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by pranaygp** [comment]
https://xkcd.com/844/
