### ISSUE TITLE
Ctrl + click allows to see the css styles and edit them directly without jumping to the css file

### ISSUE THREAD

**Issue by COD3BREAK3R** [pranaygp/vscode-css-peek#64]
I would like the extension to ctrl + click on a css class to always show its attributes and properties and allow to change them directly without having to jump to the original document, because this only happens when there are several references to that same css attribute. Also add a button at the bottom of that window that says: Go to File

**Comment by COD3BREAK3R** [comment]
If you could add the options mentioned in the title and also add native support for PHP, then your extension would be the best of all.

Thanks :)

**Comment by pranaygp** [comment]
Same issue as I described in #65 , UI changes are out of control from an extension since VSCode handles these
