### ISSUE TITLE
Make the inline window be movable , resizable and delete redundant grey box .

### ISSUE THREAD

**Issue by Spanoudakhs** [pranaygp/vscode-css-peek#65]
![Screenshot from 2019-07-04 15-06-05](https://user-images.githubusercontent.com/45520375/60665691-dd200d80-9e6d-11e9-8fba-62c0cdd989bd.png)

**Comment by pranaygp** [comment]
Unfortunately this is out of control for a VSCode extension. VSCode provides extensions an API to use to return definitions when a "Peek" request is made, while VSCode handles the UI around it.

Feel free to create an Issue here (https://github.com/microsoft/vscode/issues). I'd love to upvote 👍
