### ISSUE TITLE
Excluding React Component

### ISSUE THREAD

**Issue by VimLeSai** [pranaygp/vscode-css-peek#68]
When i click on React componet then it should open the that file or componet according to another installed extension. But what's happning is after installing it shows css file on click of components. it should only work when click on className or class in file.

**Comment by pranaygp** [comment]
Fixed in version 3.3.1

**Comment by pranaygp** [comment]
for the record, it will still show css matches for lowercase components like `<div ...` or `<h1 ...` but I excluded CSS Peek from returning anything when clicking on `<Component ...`
