### ISSUE TITLE
Upgrade to new "rootPath" API

### ISSUE THREAD

**Issue by pranaygp** [pranaygp/vscode-css-peek#70]
I received this in the mail

> Hello! 
> 
> I am a developer on the VS Code team at Microsoft. If you are receiving this email, then you are the owner of a VS Code extension that appears to be using the `vscode.workspace.rootPath` API. This is a deprecated property and may not work as expected. I am reaching out to encourage you to upgrade your extension to properly support multi-root workspaces by switching to  `vscode.workspace.workspaceFolders` instead. 
> 
> Find more info about supporting multi-root workspaces here: https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath
> 
> And more details about this issue here: https://github.com/microsoft/vscode/issues/69335
>
>
> Thanks!

This *should* be a straightforward migration. I'd love to collaborate on a PR for this since I have little time these days

**Comment by akosasante** [comment]
👋 I'd be interested in taking a look at this; though from a quick search, I don't currently see where this is being used apart from a single test?

**Comment by pranaygp** [comment]
yup, looks like it's just in the test @akosasante 

really simple fix I believe

**Comment by pranaygp** [comment]
Yup, Fixed
