### ISSUE TITLE
Support for Blade files

### ISSUE THREAD

**Issue by MarcinKilarski** [pranaygp/vscode-css-peek#72]
Hi, 

Unfortunately, your extension does not work on in files that end with .blade.php, which are [Blade](https://laravel.com/docs/5.8/blade) files. We use Blade templating engine to write all PHP code. 

It works just fine if we change the file extension to .php, without any code changes inside the file.

I have tried adding blade.php, blade and .php file extensions to the list of vscode language names where the extension should be used in the extension settings. Unfortunately, it didn't work. Is it possible to make your extension work with Blade files?

It would make our life much easier.

**Comment by pranaygp** [comment]
Can you try setting the language mode on that VSCode file to php? My guess
is vscode sets it to blade or something else instead of php, but if the
extension is just .php, it'll set it to php.

If that works for you, it'll be a really easy fix on the extension since
we'll just need to add "blade" to an array somewhere and it'll make for a
really easy PR I can accept 😉

**Comment by MarcinKilarski** [comment]
Thanks for your quick reply. 

I can confirm that setting the language mode on the VSCode file to PHP made your extension work just fine.

 It would be great if you could add "blade" to an array. 

I am looking forward to the next extension update :)

**Comment by MarcinKilarski** [comment]
Hi,

Could you tell me when do you plan to release the new version of the extension with this change?

**Comment by pranaygp** [comment]
It actually shouldn't need an update. Just add "blade" to your VSCode configuration for the "css_peek.peekFromLanguages" setting

**Comment by MarcinKilarski** [comment]
Sorry, I was not aware of this setting. I have added the blade to "css_peek.peekFromLanguages" setting and everything works fine. Thank you.

However, I would consider adding a blade to the default list of languages, because it is something between PHP and HTML. 

Thanks again :)
