### ISSUE TITLE
auto refresh problem

### ISSUE THREAD

**Issue by www987** [pranaygp/vscode-css-peek#73]
After I create new class and style this class I cant peek it. I need to refresh visual studio to peek this class. How to auto refresh classes, ids ... or refresh on demand?

**Comment by chackmool** [comment]
I have the same problem any solution??

**Comment by www987** [comment]
> I have the same problem any solution??

I saw that other extensions with the same purpose, have the same problem. So probably you need to just reload window after you add new class..

**Comment by pranaygp** [comment]
Sorry for not responding earlier @www987 
I can confirm this issue on my end (which is new from when I first released CSS Peek. It looks like it's caused by updates to VSCode since then).

I'm looking into it. I'd love your help too if you wanna take a stab at the issue :)

**Comment by pranaygp** [comment]
Fixed in version 3.3.0

**Comment by HanMoeHtet** [comment]
@pranaygp It is happening again in v4.2.0.
