### ISSUE TITLE
No definition found

### ISSUE THREAD

**Issue by Dzsepetto** [pranaygp/vscode-css-peek#74]
When i press f12 it says "No definiton found". Peek and hover just dont work. I tried everything but no success. The output says nothing. Help pls (win10)

**Comment by EKtorMakras** [comment]
I have the same issue too...

**Comment by chackmool** [comment]
He also the same. On osx

**Comment by chanthapanya** [comment]
you have to open your folder in vs code after that open your file then it will work, the reason why you have an issue is vs code doesn't know the address of your CSS file.

**Comment by Dzsepetto** [comment]
> you have to open your folder in vs code after that open your file then it will work, the reason why you have an issue is vs code doesn't know the address of your CSS file.

Thank you, i wasted so many hours because of this. I thought i have tried everything but it seems i didn't check the easiest one.
