### ISSUE TITLE
Will this extension let me jump from an import statement in a js file to the source css file?

### ISSUE THREAD

**Issue by joshglenn** [pranaygp/vscode-css-peek#77]
I have a simple index.js file that has an `import './index.css'` statement.

I want to right-click and go to that file.

I installed it and tried, but vscode says it cannot find the definition>

 Should I be able to that with this plugin?

**Comment by vaclavbenes** [comment]
its not working for `import './index.scss` . Tested with vue.js project. If its possible add this one to css_peak.

**Comment by pranaygp** [comment]
nope, this doesn't work on `import` statements. For that, please use [file peek](https://github.com/abierbaum/vscode-file-peek).

I personally use both, file peek and css peek
