### ISSUE TITLE
New HTML elements not being connected to CSS definitions

### ISSUE THREAD

**Issue by jimmy1830** [pranaygp/vscode-css-peek#78]
[Codecademy - Dasmoto.zip](https://github.com/pranaygp/vscode-css-peek/files/4549631/Codecademy.-.Dasmoto.zip)
I've looked in as many related previous threads, but I couldn't seem to find my answer. The code attached is just for a simple website, but css-peek has been fidgety. It seems that after I add an HTML element and a corresponding CSS definition, CSS-Peek doesn't recognize the connection until I reload my coding window, and even that is sometimes finicky. 
Additionally, when I insert a CSS definition in the top/middle of my style sheet, the HTML "Go to definition" option doesn't update where each definition is, which leads to incorrectly-highlighted code.
And then stuff starts to break once I add and then remove block comments in the CSS. Any thoughts?

I'm using a MacBook with Cataline 10.15.4 and the latest VSCode version (1.44 I believe)

**Comment by pranaygp** [comment]
Just resolved this issue. Please update CSS Peek to 3.3.0
