### ISSUE TITLE
[Error] Request textDocument/definition failed.

### ISSUE THREAD

**Issue by tinyTea** [pranaygp/vscode-css-peek#83]
Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
Code: -32603 

vscode version: 1.47.2

**Comment by pranaygp** [comment]
just pushed a number of updates. can you update to CSS Peek 3.2.0+
It should be resolved :)

**Comment by pranaygp** [comment]
Closing in favor of #42

**Comment by baoxin** [comment]
[Error - 10:32:46] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read properties of undefined (reading 'toUpperCase')
  Code: -32603 

vscode version: 1.87.2 (Universal)
