### ISSUE TITLE
Peek feature doesn't work (Ctrl+Shift+F12)

### ISSUE THREAD

**Issue by arnofly** [pranaygp/vscode-css-peek#87]
Hi,

I don't know very well VS Code, that I use essentially for a quick edit, but for a new little project I wanted to use it, because many add-ons are great!

The peek feature looks to doesn't work with HTML and PHP files. The CSS classes are in a CSS files.
The cursor is in my CSS class or id and then I press the shortcut **Ctrl+Shift+F12**, nothing happen on my computer. The **Ctrl+mouse hover** and **F12** shortcuts are OK.

Otherwise, **Ctrl+click** open CCS file as **F12** do, but I prefer **Ctrl+click**. 

Thx

**Comment by pranaygp** [comment]
can you check your keyboard preferences, or use `ctrl+shift+p` and search for the "peek" feature there?
