### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Khacky** [pranaygp/vscode-css-peek#88]
- Issue Type: `Performance`
- Extension Name: `vscode-css-peek`
- Extension Version: `4.0.0`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\scart\pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by pranaygp** [comment]
Merging with #41
