### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by sysoev-dev** [pranaygp/vscode-css-peek#89]
Hello! Every time I open Visual studio code I get this error.
![1](https://user-images.githubusercontent.com/24270731/90962518-61da4a80-e4b9-11ea-80db-e6ba9d3bf00b.png)

Version: 1.48.1 (for Windows)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
ОС: Windows_NT x64 10.0.19041

**Comment by pranaygp** [comment]
@sysoev-dev what CSS Peek version are you using?

**Comment by sysoev-dev** [comment]
@pranaygp v4.0.0

**Comment by pranaygp** [comment]
Reproduction steps:
* Startup VS Code
* Open a brand new file (not in a workspace, just using Cmd+N)
* set the language mode to "typescript"
![image](https://user-images.githubusercontent.com/1797812/91106861-a6d0bf00-e628-11ea-8b56-fefd1b3c5a5c.png)

**Comment by arekuusa** [comment]
+1

**Comment by rain84** [comment]
+2
The same problem

Steps to reproduction

1.  Open new instance of VS Code
2. New file with the "Command+N" (I am a Mac user)
3. Change language mode with "Command+K, M"

After that error occurred

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/1732547/99878432-54e30980-2c16-11eb-9b8f-1c63988b3e68.png">

**Comment by pranaygp** [comment]
This has been fixed in version v4.3.4
