### ISSUE TITLE
Extensão causa alta carga de cpu

### ISSUE THREAD

**Issue by MiguelCararine** [pranaygp/vscode-css-peek#90]
- Issue Type: `Performance`
- Extension Name: `vscode-css-peek`
- Extension Version: `4.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\miihc\pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by pranaygp** [comment]
Duplicate of #41
