### ISSUE TITLE
If a css file is modified, code navigation doesn't work correctly

### ISSUE THREAD

**Issue by dvsekhvalnov** [pranaygp/vscode-css-peek#92]
Hello, 

question, it seems extension is not indexing changes in .css files until vscode process restarted?

After i edit and save css files (add or remove css rules) all jump-to-definition and show-definition is off, pointing to wrong location in .css file. Basically it points to position in .css file before edit.

Restarting vscode - obviously fixes it. 

Details: OSX,  vscode v1.49.0, CSS Peek v4.0.0

**Comment by pranaygp** [comment]
This sounds like a real bug. I'll look into it and hopefully have a patch out. It's a busy time for me so don't expect anything soon - I'd love any help on this with contributions 😃

**Comment by Hacktinium** [comment]
Hi @pranaygp,

Still having this issue. Any chance of a patch/fix on the way? 

Thanks

**Comment by pranaygp** [comment]
@Hacktinium fixed :)
